[feat] 게시글 API 리팩토링
nodak-v2/Nodak-Server pull request #55
Opened 2024-05-09 07:34 UTC by wooyong99

## Description ✍️
* ConstraintViolationException 핸들러 추가
  * Controller 계층에서 PostRequest를 수정 기능에서도 사용하기 때문에 Service 계층에서 Entity로 변환 시, 에러 핸들러 추가
* 좋아요 기능 중복 테스트 에러 해결
  * 좋아요 취소 후, 다시 좋아요가 되지 않는 버그 해결
* PostController @AuthorizationRequired 어노테이션 추가
* findOne return 값 Optional Wrapping 

## Merge 전 체크 리스트 ✅
- [ ] Backend 컨벤션을 잘 지켰나요?
- [ ] 오류 없이 해당 기능이 잘 동작되나요?
- [ ] 모든 리뷰어의 승인을 받았나요?

2024-05-09 10:12 UTC, Jungsu-lilly requested changes
수고하셨습니다.👍

근데 저희 게시글 상세 조회에서, 로그인된 유저가 쓴 글인지 여부를 나타내는 필드를 추가해달라는 말이 있어서요. 해당 부분 추가된 걸까요?

2024-05-10 00:26 UTC, wooyong99 commented
> 수고하셨습니다.👍
> 
> 근데 저희 게시글 상세 조회에서, 로그인된 유저가 쓴 글인지 여부를 나타내는 필드를 추가해달라는 말이 있어서요. 해당 부분 추가된 걸까요?

2024-05-10 05:27 UTC, Jungsu-lilly approved these changes
수고하셨습니다!

2024-05-10 14:50 UTC, dev-khg approved these changes
고생하셨습니다.

2024-05-10 14:50 UTC, dev-khg commented on src/main/java/com/server/nodak/domain/post/repository/StarPostRepository.java
> +    List<StarPost> findByUserIdAndPostId(Long userId, Long postId);
좋아요 내역은 1개만 있을 것 같은데, 리스트로 받은 이유가 혹시 있을까요?!

2024-05-11 00:09 UTC, wooyong99 commented on src/main/java/com/server/nodak/domain/post/repository/StarPostRepository.java
> +    List<StarPost> findByUserIdAndPostId(Long userId, Long postId);
제가 오해를 하고 코드를 잘못 작성한 것 같습니다 !
피드백 감사합니다 ! :)

2024-05-11 00:14 UTC, merged